const fs = require('fs');

const unformattedData = [
  'Abkhazians',
  'Adjarians',
  'Afghanistan',
  'Afrian-American',
  'Afrikaners',
  'Afro-Brazilians',
  'Ainu',
  'Aka',
  'Albanians',
  'Algerians',
  'Amhara',
  'Andalusians',
  'Andhras',
  'Andorrans',
  'Angolans',
  'Antiguans',
  'Araucanians',
  'Argentines',
  'Armenians',
  'Asháninka',
  'Asmat',
  'Australian Aborigines',
  'Australians',
  'Austrians',
  'Aymara',
  'Azande',
  'Azerbaijanis',
  'Baganda',
  'Bahamians',
  'Bahrainis',
  'Bakongo',
  'Balinese',
  'Baluchi',
  'Bangladeshis',
  'Banyankole',
  'Barbadians',
  'Barbudans',
  'Basques',
  'Bedu',
  'Belarusans',
  'Belgians',
  'Belizeans',
  'Bemba',
  'Bengalis',
  'Beninese',
  'Bhutanese',
  'Bolivians',
  'Bosnians',
  'Brahui',
  'Brazilians',
  'Bretons',
  'Bulgarians',
  'Burkina Faso',
  'Burkinabe',
  'Burman',
  'Burmese',
  'Burundians',
  'Cambodia',
  'Cameroonians',
  'Canadians',
  'Cape Coloreds',
  'Cape Verdeans',
  'Castilians',
  'Catalans',
  'Central Africans',
  'Chadians',
  'Chagga',
  'Chakmas',
  'Cham',
  'Chechens',
  'Chewa and other Maravi Groups',
  'Chileans',
  'Chinese',
  'Chukchi',
  'Colombians',
  'Congolese',
  'Costa Ricans',
  'Cote dIvoire',
  'Creoles of Sierra Leone',
  'Croats',
  'Cubans',
  'Cunas',
  'Cyprus',
  'Czechs',
  'Danes',
  'Dinka',
  'Djiboutians',
  'Dominicans',
  'Dong',
  'Druze',
  'Ecuadorans',
  'Efe and Mbuti',
  'Egyptians',
  'Emirians',
  'English',
  'Equatorial Guineans',
  'Eritreans',
  'Estonians',
  'Ethiopians',
  'Ewenki',
  'Fiji',
  'Filipinos',
  'Finns',
  'Flemings',
  'French',
  'French Canadians',
  'French Guianans',
  'Frisians',
  'Fulani',
  'Gabonese',
  'Galicians',
  'Gambians',
  'Garifuna',
  'Georgians',
  'Germans',
  'Ghanaians',
  'Gikuyu',
  'Gonds',
  'Greek Cypriots',
  'Greeks',
  'Grenadians',
  'Guajiros',
  'Guaranís',
  'Guatemalans',
  'Guineans',
  'Gujaratis',
  'Gusii',
  'Guyanans',
  'Haitians',
  'Han',
  'Hausa',
  'Hazaras',
  'Herzegovina',
  'Hiligaynon',
  'Hill Tribespeople',
  'Hondurans',
  'Hungarians',
  'Hutu',
  'Iatmul',
  'Icelanders',
  'Igbo',
  'Ilocanos',
  'Indians',
  'Indo-Fijians',
  'Indonesians',
  'Inuit',
  'Iranians',
  'Iraqis',
  'Irish',
  'Israelis',
  'Italians',
  'Ivoirians',
  'Jamaicans',
  'Japanese',
  'Javanese',
  'Jivaro',
  'Jordanians',
  'Kalenjin',
  'Kammu',
  'Karakalpaks',
  'Karens',
  'Kayapos',
  'Kazaks',
  'Kenyans',
  'Khmer',
  'Kittitians and Nevisians',
  'Kurds',
  'Kuwaitis',
  'Kyrgyz',
  'Lao',
  'Laotians',
  'Latvians',
  'Lebanese',
  'Lesotho',
  'Liberians',
  'Libyans',
  'Liechtensteiners',
  'Lithuanians',
  'Luhya',
  'Luo',
  'Luxembourgers',
  'Maasai',
  'Macedonians',
  'Maan (Marsh Arabs)',
  'Malagasy',
  'Malawi',
  'Malays',
  'Malians',
  'Malinke',
  'Man (Manchus)',
  'Maori',
  'Marathas',
  'Maronites',
  'Mauritanians',
  'Maya',
  'Melanesians',
  'Melpa',
  'Mexicans',
  'Miao',
  'Micronesians',
  'Moldovans',
  'Monégasques',
  'Mongols',
  'Mordvins',
  'Moroccans',
  'Mossi',
  'Motu',
  'Mozambicans',
  'Namibians',
  'Nentsy',
  'Nepalis',
  'Netherlanders',
  'New Zealanders',
  'Nicaraguans',
  'Nigerians',
  'Nigeriens',
  'Ni-Vanuatu',
  'Norwegians',
  'Nyamwezi',
  'Omanis',
  'Oriya',
  'Oromos',
  'Páez',
  'Pakistanis',
  'Palestinians',
  'Pamiri',
  'Panamanians',
  'Paraguayans',
  'Pashtun',
  'Pemon',
  'Peruvians',
  'Poland',
  'Poles',
  'Polynesians',
  'Portuguese',
  'Punjabis',
  'Qataris',
  'Quechua',
  'Rajputs',
  'Republic of Korea',
  'Roma',
  'Romanians',
  'Russians',
  'Rwandans',
  'Salvadorans',
  'Sami',
  'Sammarinese',
  'Samoans',
  'Saudis',
  'Scots',
  'Senegalese',
  'Seychellois',
  'Shambaa',
  'Shans',
  'Sherpas',
  'Sierra Leone',
  'Sinhalese',
  'Slovaks',
  'Slovenes',
  'Somalis',
  'Songhay',
  'Sotho',
  'South Africa',
  'South Koreans',
  'Spaniards',
  'Sri Lanka',
  'St. Lucians',
  'St. Vincentians',
  'Sudanese',
  'Sumu and Miskito',
  'Sundanese',
  'Surinamese',
  'Swahili',
  'Swazis',
  'Swedes',
  'Swiss',
  'Syrians',
  'Tajiks',
  'Tamils',
  'Tanzanians',
  'Tatars',
  'Thai',
  'Tibetans',
  'Tigray',
  'Tonga',
  'Trinidadians and Tobagonians',
  'Tuareg',
  'Tunisians',
  'Turkmens',
  'Turks',
  'Tutsi',
  'Ugandans',
  'Uighurs',
  'Ukrainians',
  'United Arab Emirates',
  'United Kingdom',
  'Uruguayans',
  'Uzbeks',
  'Vanuatu',
  'Venezuelans',
  'Vietnamese',
  'Walloons',
  'Welsh',
  'Western Samoa',
  'Wolof',
  'Xavante',
  'Xhosa',
  'Yemenis',
  'Yoruba',
  'Zambians',
  'Zhuang',
  'Zimbabweans',
  'Zulu',
  'Other',
];
const lintedData = [];

const lintingData = new Promise((resolve) => {
  unformattedData.forEach((rawData) => {
    lintedData.push({ culture: rawData });
  });
  resolve(lintedData);
});
lintingData.then((data) => {
  fs.writeFile(
    '../constants/formattedCultures.json',
    JSON.stringify(data, null, 2),
    'utf-8',
    (err) => {
      // eslint-disable-next-line no-console
      if (err) {
        // eslint-disable-next-line no-console
        console.log(err);
      }
    }
  );
});
